### ISSUE TITLE
TypeError: DoubleStreamBlock.forward() got an unexpected keyword argument 'attn_mask'

### ISSUE THREAD

**Issue by pendave** [XLabs-AI/x-flux-comfyui#160]
0%|                                                                                           | 0/20 [00:11<?, ?it/s]
!!! Exception during processing !!! DoubleStreamBlock.forward() got an unexpected keyword argument 'attn_mask'
Traceback (most recent call last):
  File "E:\ComfyUI_Portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, p
re_execute_cb=pre_execute_cb)
  File "E:\ComfyUI_Portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=exec
ution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI_Portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_Portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI_Portable\ComfyUI\nodes.py", line 1503, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=d
enoise)
  File "E:\ComfyUI_Portable\ComfyUI\nodes.py", line 1470, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "E:\ComfyUI_Portable\ComfyUI\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_
step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disabl
e_pbar=disable_pbar, seed=seed)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 1013, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_i
mage=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 911, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 897, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 866, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 850, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 707, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_
pbar, **self.extra_options)
  File "E:\ComfyUI_Portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\k_diffusion\sampling.py", line 155, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 379, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 832, in __call__
    return self.predict_noise(*args, **kwargs)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 835, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive",
 None), self.cfg, model_options=model_options, seed=seed)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 359, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 195, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\samplers.py", line 308, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\model_base.py", line 129, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
  File "E:\ComfyUI_Portable\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\model_base.py", line 158, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options
, **extra_conds).float()
  File "E:\ComfyUI_Portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_im
pl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI_Portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ComfyUI_Portable\ComfyUI\comfy\ldm\flux\model.py", line 204, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control, transformer_options, attn_ma
sk=kwargs.get("attention_mask", None))
  File "E:\ComfyUI_Portable\ComfyUI\comfy\ldm\flux\model.py", line 143, in forward_orig
    img, txt = block(img=img,
  File "E:\ComfyUI_Portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_im
pl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI_Portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: DoubleStreamBlock.forward() got an unexpected keyword argument 'attn_mask'

![image](https://github.com/user-attachments/assets/0fd2a78b-d535-41af-be85-b9ebcc571404)

**Comment by craftogrammer** [comment]
I am also getting the same issue.

![image](https://github.com/user-attachments/assets/35e77195-2a3e-49f1-a841-01959fcdb574)

`!!! Exception during processing !!! DoubleStreamBlock.forward() got an unexpected keyword argument 'attn_mask'
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 633, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 897, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 866, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 850, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 707, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\k_diffusion\sampling.py", line 1098, in sample_deis
    denoised = model(x_cur, t_cur * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 379, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 832, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 835, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 359, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 195, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 308, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\model_base.py", line 130, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\model_base.py", line 159, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 576, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\ldm\flux\model.py", line 189, in forward
    def forward(self, x, timestep, context, y, guidance, control=None, transformer_options={}, **kwargs):
  File "D:\ComfyUI\comfy\ldm\flux\model.py", line 143, in forward_orig
    img, txt = block(img=img,
               ^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DoubleStreamBlock.forward() got an unexpected keyword argument 'attn_mask'
`

**Comment by arakinas** [comment]
Same

**Comment by rollingcookies** [comment]
Same problem! Recently updated Comfy, maybe it is connected with it?

**Comment by Moxie1776** [comment]
Following, same.

**Comment by h3clikejava** [comment]
same

**Comment by vmasrani** [comment]
same

**Comment by africa1207** [comment]
same here

**Comment by dxdpxl** [comment]
exactly the same

**Comment by dxdpxl** [comment]
A reset to ComfyUI v.3.0.7 with "git checkout v0.3.7" inside the lower comfyui folder and we can continue using x-flux. Thanks to the guys who posted the solution in a ComfyUI-PuLID-Flux-Enhanced issue thread. Hope they will fix it soon!

**Comment by mayo-Z** [comment]
same

**Comment by AdgDean** [comment]
@dxdpxl Thanks Man for Share

**Comment by amirabbbbas** [comment]
Here's the option in the comfyui for downgrading to 0.3.7 which solved the problem
![image](https://github.com/user-attachments/assets/b3ec6a3a-b039-4b6e-a05f-5b2fe1af2539)
![image](https://github.com/user-attachments/assets/9639efac-cd42-4812-b722-12eaf24d0029)

**Comment by pendave** [comment]
> Here's the option in the comfyui for downgrading to 0.3.7 which solved the problem ![image](https://private-user-images.githubusercontent.com/53795188/400207275-b3ec6a3a-b039-4b6e-a05f-5b2fe1af2539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxMzMwODgsIm5iZiI6MTczNjEzMjc4OCwicGF0aCI6Ii81Mzc5NTE4OC80MDAyMDcyNzUtYjNlYzZhM2EtYjAzOS00YjZlLWEwNWYtNWIyZmUxYWYyNTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDAzMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNTVkN2Y0OTBlM2ZkNmI0YzdjNTkwMjM4ZGI4Y2NjZWJmODE4MmU3MzUwMTMyZmIyZTZjMWVhZjdkYzY1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.18HpF1WCEnhSMIh3mROu5igAthAXO75vbffhSGmA9NE) ![image](https://private-user-images.githubusercontent.com/53795188/400207288-9639efac-cd42-4812-b722-12eaf24d0029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxMzMwODgsIm5iZiI6MTczNjEzMjc4OCwicGF0aCI6Ii81Mzc5NTE4OC80MDAyMDcyODgtOTYzOWVmYWMtY2Q0Mi00ODEyLWI3MjItMTJlYWYyNGQwMDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDAzMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NjY5NWQwMzY2ZDY1YTgyNzRjOTM0N2ZmN2I0MmJlMjQ4ZTc3Njg3NjQ3NDZhZmQyMjIwZWUzNzk5OWFiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HDEiMrpCEL_syDUWWBlQB-1oX7YhOyZXyhRIdA9PD5M)

![image](https://github.com/user-attachments/assets/7eee6eb3-45f4-4c16-ac14-3f92b2e68dfb)
How could I let "Switch ComfyUI" displayed?

**Comment by dxdpxl** [comment]
> How could I let "Switch ComfyUI" displayed?

I don't know about your question, maybe this future is only available in the latest version of comfyui...

but to get you to downgrade comyfui, do the following:
fully close comfyui and go into your lower comfyui folder "X:\ComfyUI\ComfyUI" (while X is the drive where you installed it), now left-click into the adressbar of the ComfyUI folder and write "**cmd**" and press enter (without quotation marks), in the following opened cmd window enter "**git checkout v0.3.7**" (again without quotation marks) and press enter, wait until its finished, voila comfyui is downgraded.

![comfy](https://github.com/user-attachments/assets/caf9e8b9-c644-44c3-824d-f060ccae89bf)

**Comment by pendave** [comment]
> > How could I let "Switch ComfyUI" displayed?
> 
> I don't know about your question, maybe this future is only available in the latest version of comfyui...
> 
> but to get you to downgrade comyfui, do the following: fully close comfyui and go into your lower comfyui folder (note lowercase letters), left-click into the adressbar of the comfyui folder and write "**cmd**" and press enter (without quotation marks), in the following opened cmd window enter "**git checkout v0.3.7**" (again without quotation marks) and press enter, wait until its finished, voila comfyui is downgraded.

![image](https://github.com/user-attachments/assets/978a9d03-6287-400f-83c5-40a9cee8c343)

Actually I updated ComfyUI version to the latest:

### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Version: v0.3.10-35-g916d1e1 | Released on '2025-01-06'

But I can't find the **lower comfyui folder**, you can see that above.

**Comment by dxdpxl** [comment]
You are already in the right folder "E:\ComfyUI\ComfyUI\"

Sorry for the confusion, mine is only lowercase, I don't know why, but I will correct my advice.

**Comment by pendave** [comment]
> You are already in the right folder "E:\ComfyUI\ComfyUI"
> 
> Sorry for the confusion, mine is only lowercase, I don't know why, but I will correct my advice.

I always execute CMD that way. But 

E:\ComfyUI_Portable\ComfyUI>git checkout v0.3.7
error: Your local changes to the following files would be overwritten by checkout:
        folder_paths.py
Please commit your changes or stash them before you switch branches.
Aborting

E:\ComfyUI_Portable\ComfyUI>

Maybe I could download V0.3.7 from ComfyUI Release https://github.com/comfyanonymous/ComfyUI/releases and put it another path, then mklink and share the models etc. resources from the E:\ComfyUI_Portable one. Hope the coder fixes the bug in the future.

**Comment by dxdpxl** [comment]
> I always execute CMD that way.

Sorry then i can't help, I don't know anything about this error. I attached a photo of what it should look like...

![comfy1](https://github.com/user-attachments/assets/6a67e14b-b222-4c28-b0a5-d9e32fe4e12f)

**Comment by amirabbbbas** [comment]
> > Here's the option in the comfyui for downgrading to 0.3.7 which solved the problem ![image](https://private-user-images.githubusercontent.com/53795188/400207275-b3ec6a3a-b039-4b6e-a05f-5b2fe1af2539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxMzMwODgsIm5iZiI6MTczNjEzMjc4OCwicGF0aCI6Ii81Mzc5NTE4OC80MDAyMDcyNzUtYjNlYzZhM2EtYjAzOS00YjZlLWEwNWYtNWIyZmUxYWYyNTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDAzMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNTVkN2Y0OTBlM2ZkNmI0YzdjNTkwMjM4ZGI4Y2NjZWJmODE4MmU3MzUwMTMyZmIyZTZjMWVhZjdkYzY1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.18HpF1WCEnhSMIh3mROu5igAthAXO75vbffhSGmA9NE) ![image](https://private-user-images.githubusercontent.com/53795188/400207288-9639efac-cd42-4812-b722-12eaf24d0029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxMzMwODgsIm5iZiI6MTczNjEzMjc4OCwicGF0aCI6Ii81Mzc5NTE4OC80MDAyMDcyODgtOTYzOWVmYWMtY2Q0Mi00ODEyLWI3MjItMTJlYWYyNGQwMDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDAzMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NjY5NWQwMzY2ZDY1YTgyNzRjOTM0N2ZmN2I0MmJlMjQ4ZTc3Njg3NjQ3NDZhZmQyMjIwZWUzNzk5OWFiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HDEiMrpCEL_syDUWWBlQB-1oX7YhOyZXyhRIdA9PD5M)
> 
> ![image](https://private-user-images.githubusercontent.com/1331881/400285550-7eee6eb3-45f4-4c16-ac14-3f92b2e68dfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNzMwODgsIm5iZiI6MTczNjE3Mjc4OCwicGF0aCI6Ii8xMzMxODgxLzQwMDI4NTU1MC03ZWVlNmViMy00NWY0LTRjMTYtYWMxNC0zZjkyYjJlNjhkZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMTQxMzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFmMTI2NjZjOGFiYjc0NGIzODVkYTM4MWM1NmVjMTdiY2ZkMTM2ZTBlYjUyYmEwZjhiYzE4ZDM5YTgyYzI1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XTwtIGHj6ivss0x6q03YZknTHeDXg_Mnut4w39XDf2k) How could I let "Switch ComfyUI" displayed?



First Update all and choose every update option that you see , restart and then the option will appear for you

**Comment by dxdpxl** [comment]
> I always execute CMD that way.

Did you edited/changed anything inside the folder_paths.py?

Maybe try to delete (backup!) the problematic file...
Then cmd **_run git reset --hard_** and after that the checkout again

**Comment by Aloukik21** [comment]
any good solution yet?

**Comment by ryujongsu** [comment]
I did Update ComplyUI and it was solved.

**Comment by rollingcookies** [comment]
> I did Update ComplyUI and it was solved.

What version/commit did you upgrade to?

![image](https://github.com/user-attachments/assets/17a21557-9527-4a4b-80bb-173c9895b4e6)

**Comment by dxdpxl** [comment]
> I did Update ComplyUI and it was solved.

No it's not solved! It happens with every version above 0.3.7! I update daily to test it.

Seems like this Git is dead and won't get any updates...

**Comment by AdgDean** [comment]
Sorry so much I know this is GitHub no Twitter but....... Generally, it's virtually impossible to be productive with UncomfyUI. As an artist, I understand that programs like HoudiniFX, Maya, Nuke, and Flame are complex, but this UncomfyUI nightmare makes no sense. There are too many technical hurdles to overcome just to create a single image; something is always broken. Most artists rely on a tech-savvy person to set up the workflow. No matter what you do with cfgs, Denoise, IPAdapter, ControlNet, or how well you think you understand it, you'll spend countless hours and days trying to achieve anything. It's completely illogical.

**Comment by rollingcookies** [comment]
> Sorry so much I know this is GitHub no Twitter but....... Generally, it's virtually impossible to be productive with UncomfyUI. As an artist, I understand that programs like HoudiniFX, Maya, Nuke, and Flame are complex, but this UncomfyUI nightmare makes no sense. There are too many technical hurdles to overcome just to create a single image; something is always broken. Most artists rely on a tech-savvy person to set up the workflow. No matter what you do with cfgs, Denoise, IPAdapter, ControlNet, or how well you think you understand it, you'll spend countless hours and days trying to achieve anything. It's completely illogical.

Another fighter has given up :')

**Comment by dxdpxl** [comment]
The ignorance of this issue and the fact that there is not even an explanation if it will be fixed or never fixed because they abandoned the project says everything about the developers of XLabs-AI.

x-flux-comfyui should be banned from the ComfyUI Manager for this reason and this repro should be closed/hidden.

**Comment by 3dluvr** [comment]
Edit this file **x-flux-comfyui\xflux\src\flux\modules\layers.py** in your custom_nodes/ ComfyUI folder.

In line **296**, add to the method parameters `**attention_kwargs`, so it looks like this:

```
def forward(self, img: Tensor, txt: Tensor, vec: Tensor, pe: Tensor, **attention_kwargs) -> tuple[Tensor, Tensor]:
    return self.processor(self, img, txt, vec, pe, **attention_kwargs)
```

Restart ComfyUI.

Profit.

**Comment by dxdpxl** [comment]
> Edit this file **x-flux-comfyui\xflux\src\flux\modules\layers.py** in your custom_nodes/ ComfyUI folder.

Thanks, but that gives me another error.

![Image](https://github.com/user-attachments/assets/d7a11f49-c56f-4961-8dc2-5e4c3cce407d)

![Image](https://github.com/user-attachments/assets/5b8f3346-471b-4337-a331-a47f089d497f)

# ComfyUI Error Report
## Error Details
- **Node ID:** 24
- **Node Type:** ApplyFluxIPAdapter
- **Exception Type:** TypeError
- **Exception Message:** ImageProjModel.forward() missing 3 required positional arguments: 'txt', 'vec', and 'pe'
## Stack Trace

  File "C:\ComfyUI\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\ComfyUI\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI\comfyui\custom_nodes\x-flux-comfyui\nodes.py", line 615, in applymodel
    ip_projes = ip_adapter_flux['ip_adapter_proj_model'](out.to(ip_projes_dev, dtype=torch.bfloat16)).to(device, dtype=torch.bfloat16)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by 3dluvr** [comment]
@dxdpxl 

Are you using the latest ComfyUI though...seems to be working for me?

![Image](https://github.com/user-attachments/assets/cd2db858-0f7b-4143-876c-c9b7c9e8818b)

**Comment by dxdpxl** [comment]
Thank you for your reply! It is up to date, yes. That's interesting! After installing bnb and creating a quick workflow, I was able to narrow down the problem to something else. So yeah it works now! Looks like the new problem has to do with the unet loader from gguf / gguf model. If I load a unet safetensor with the bnb loader, the error is gone. A bit annoying, because all my flux workflows rely on the gguf models, yay.

**Comment by dxdpxl** [comment]
> [@dxdpxl](https://github.com/dxdpxl)
> 
> Are you using the latest ComfyUI though...seems to be working for me?

Thank you for your reply! It is up to date, yes. That's interesting! After installing bnb and creating a quick workflow, I was able to narrow down the problem to something else. So yeah it works now! Looks like the new problem has to do with the unet loader from gguf / gguf model. If I load a unet safetensor with the bnb loader, the error is gone. A bit annoying, because all my flux workflows rely on the gguf models, yay.

**Comment by dxdpxl** [comment]
> [@dxdpxl](https://github.com/dxdpxl)
> 
> Are you using the latest ComfyUI though...seems to be working for me?
> 
Thanks for your reply! Yes, I use the latest 0.3.12. I installed bnb, rebuild your workflow you showed, downloaded the models from your workflow, but same error.

* deleted (Earlier I thought it works, sorry for the confusion and the double posts)

**Comment by 3dluvr** [comment]
@dxdpxl 

I'm using the same version 0.3.12 and have bunch of other nodes in it, Python 3.12.7.

I packed my x-flux-comfyui node folder and attached it here - I'm really not sure why it wouldn't work otherwise.

[x-flux-comfyui.zip](https://github.com/user-attachments/files/18551712/x-flux-comfyui.zip)

**Comment by dxdpxl** [comment]
> [@dxdpxl](https://github.com/dxdpxl)
> 
> I'm using the same version 0.3.12 and have bunch of other nodes in it, Python 3.12.7.

Thanks again! Today I tested a clean install of comfyui and only the needed nodes and it works. I don't know what was wrong.

BUT, the xlabs sampler is a pure nightmare when it comes to speed, thats why I don't use it in my workflows! Rendertimes are like 1+hr for a single picture, regardless of the settings and this is ridiculous. If I switch to ksampler, which worked very well until comfyui 3.0.7 (rendertimes are here around 4+ minutes in a big workflow, depending on the settings), but with any newer comfyui, I get the errors I posted last, ofc with the edited layers.py. If I don't edited the file it is the same error like everyone else has. So sticking to v3.0.7 is the only solution and I guess this problem won't get fixed.

**Comment by 3dluvr** [comment]
@dxdpxl 

I don't find their sampler slow, but then again I only set 20 steps because I iterate a lot. I also tried generic Ksampler and I did not get any errors, although it does not have some parameters XLabs sampler does, they are both equally slow for me (RTX 3090) or maybe I expect too much, LOL.

**Comment by dxdpxl** [comment]
> [@dxdpxl](https://github.com/dxdpxl)

Same here, 20 steps and I'm using smaller GGUF models that should perform even better. I don't know what could be the reason that the XLabs sampler is so slow for me. I have tried various solutions and none of them have helped. I'm not the only one with this problem; for some, it's fast, for others, it's just mediocre, and for others like me, it's incredibly slow. I give up... time to look for something else. It's frustrating when you have a workflow that delivers amazing results and you become somewhat dependent on the tools used, only for them not to be maintained.

**Comment by dxdpxl** [comment]
@3dluvr 

Same here, 20 steps and I'm using smaller GGUF models that should perform even better. I don't know what could be the reason that the XLabs sampler is so slow for me. I have tried various solutions and none of them have helped. I'm not the only one with this problem; for some, it's fast, for others, it's just mediocre, and for others like me, it's incredibly slow. I give up... time to look for something else. It's frustrating when you have a workflow that delivers amazing results and you become somewhat dependent on the tools used, only for them not to be maintained.

**Comment by 3dluvr** [comment]
@dxdpxl 

That's just how things are today - a fad. Someone sees a low hanging fruit and goes for it to get attention for a few moments. But there's always a next big thing just over the horizon, so rinse and repeat, while neglecting the previous work ("...it's so passé").

I'm using ComfyUI in Windows which just adds insult to injury. I'm sure it would be much faster in Linux, but I don't have my rig built up yet (watercooled 4x RTX 3090) as I'm still saving for a CPU+mobo+RAM combo. Even these 4 cards were a fortune, and I'm only using one right now. But Nvidia will release their desktop gadget (Project DIGITS) with 128GB of VRAM soon, and I feel it'll make my rig pointless.

**Comment by TristanMorelle** [comment]
> Thanks, but that gives me another error.

try this then:
```

    def forward(self, img: Tensor, txt: Tensor, vec: Tensor, pe: Tensor, **attention_kwargs) -> tuple[Tensor, Tensor]:
        return self.processor(self, img, txt, vec, pe)
```

the  attention_kwargs just contain a {'attn_mask': None} dictionary with me, so nothing more to pass really.
The above approach basically discards the additional attributes the function is not expecting which is bad practice imo but hey whatever keeps the lights on right?

**Comment by Granddyser** [comment]
> > Thanks, but that gives me another error.
> 
> try this then:
> 
> ```
> 
>     def forward(self, img: Tensor, txt: Tensor, vec: Tensor, pe: Tensor, **attention_kwargs) -> tuple[Tensor, Tensor]:
>         return self.processor(self, img, txt, vec, pe)
> ```
> 
> the attention_kwargs just contain a {'attn_mask': None} dictionary with me, so nothing more to pass really. The above approach basically discards the additional attributes the function is not expecting which is bad practice imo but hey whatever keeps the lights on right?

THANKS!!! after struggling with it for 3 months, finally it works !


EDIT: It generates faster than before

**Comment by uncle5** [comment]
1.  change ComfyUI-manager security_level to weak , in order to use git install the fucking node
location: ComfyUI-HOME/custom_nodes/ComfyUI-Manager/config.ini

2. install node from git : https://github.com/balazik/ComfyUI-PuLID-Flux

3. restart ComfyUI and your browser 

4. Done.

**Comment by Jenny20240131** [comment]
> > Thanks, but that gives me another error.
> 
> try this then:
> 
> ```
> 
>     def forward(self, img: Tensor, txt: Tensor, vec: Tensor, pe: Tensor, **attention_kwargs) -> tuple[Tensor, Tensor]:
>         return self.processor(self, img, txt, vec, pe)
> ```
> 
> the attention_kwargs just contain a {'attn_mask': None} dictionary with me, so nothing more to pass really. The above approach basically discards the additional attributes the function is not expecting which is bad practice imo but hey whatever keeps the lights on right?

Thanks a lot, it works fine now

**Comment by dxdpxl** [comment]
> try this then:
> 
> ```
> 
>     def forward(self, img: Tensor, txt: Tensor, vec: Tensor, pe: Tensor, **attention_kwargs) -> tuple[Tensor, Tensor]:
>         return self.processor(self, img, txt, vec, pe)
> ```
> 
> the attention_kwargs just contain a {'attn_mask': None} dictionary with me, so nothing more to pass really. The above approach basically discards the additional attributes the function is not expecting which is bad practice imo but hey whatever keeps the lights on right?

I confirm, it works! Thank you so much, really!
(Sorry for late reply, I had the last weeks no time for comfy)

**Comment by Thetiso** [comment]
> > Thanks, but that gives me another error.
> 
> try this then:
> 
> ```
> 
>     def forward(self, img: Tensor, txt: Tensor, vec: Tensor, pe: Tensor, **attention_kwargs) -> tuple[Tensor, Tensor]:
>         return self.processor(self, img, txt, vec, pe)
> ```
> 
> the attention_kwargs just contain a {'attn_mask': None} dictionary with me, so nothing more to pass really. The above approach basically discards the additional attributes the function is not expecting which is bad practice imo but hey whatever keeps the lights on right?

![Image](https://github.com/user-attachments/assets/a2b1e5b3-80b9-4af2-af9c-91af41afe791)

THX！！！

**Comment by AhamomentAI** [comment]
> 
> 那么试试这个：

在您的 custom_nodes/ComfyUI 文件夹中编辑此文件x-flux-comfyui\xflux\src\flux\modules\layers.py 。

在第296行，添加方法参数**attention_kwargs，如下所示：
> 
> ```
> 
>     def forward(self, img: Tensor, txt: Tensor, vec: Tensor, pe: Tensor, **attention_kwargs) -> tuple[Tensor, Tensor]:
>         return self.processor(self, img, txt, vec, pe)
> ```
> 
复制这段，覆盖原来的，重启，我测试了，正常

**Comment by CNDAXI** [comment]
> > 那么试试这个：
> > ```
> > 
> >     def forward(self, img: Tensor, txt: Tensor, vec: Tensor, pe: Tensor, **attention_kwargs) -> tuple[Tensor, Tensor]:
> >         return self.processor(self, img, txt, vec, pe)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > attention_kwargs 只包含一个 {'attn_mask': None} 字典，所以实际上没有其他需要传递的内容。上面的方法基本上丢弃了函数不需要的附加属性，在我看来，这是一种不好的做法，但无论如何，灯还是亮着的，对吧？
> 
> 我确认，有效！真的非常感谢！ （抱歉回复晚了，最近几周我没时间好好休息）

谢谢！

**Comment by zerkh** [comment]
> > Thanks, but that gives me another error.
> 
> try this then:
> 
> ```
> 
>     def forward(self, img: Tensor, txt: Tensor, vec: Tensor, pe: Tensor, **attention_kwargs) -> tuple[Tensor, Tensor]:
>         return self.processor(self, img, txt, vec, pe)
> ```
> 
> the attention_kwargs just contain a {'attn_mask': None} dictionary with me, so nothing more to pass really. The above approach basically discards the additional attributes the function is not expecting which is bad practice imo but hey whatever keeps the lights on right?

 it works for me. Greet!!

**Comment by ehudsn** [comment]
Anyone coming here and facing this same issue with the SamplerCustomAdvanced node, that can't downgrade like me, here is the fix. The file path is /path/to/ComfyUI/comfy/ldm/flux/model.py

https://gist.github.com/diveddie/d7b977e483f2ec486a3cf4f52bf9b409

I haven't deleted anything, just commented out where the attn_mask is being used because I haven't actually tested it to see if it breaks anything else yet. The issue is actually coming from ComfyUI, and I don't have time to pick up a PR but that's the root.

You can [view the issue here in the ComfyUI repo](https://github.com/comfyanonymous/ComfyUI/issues/6476).

I checked previous versions and I never see reference to an attn_mask in the DoubleStreamBlock, so I'm thinking maybe this has something to do with the underlying nn.Module?

Anyways, I think this is a downstream issue that is still open. Adapt to it, or wait for the fix?

**Comment by victormattina** [comment]
> Anyone coming here and facing this same issue with the SamplerCustomAdvanced node, that can't downgrade like me, here is the fix. The file path is /path/to/ComfyUI/comfy/ldm/flux/model.py
> 
> https://gist.github.com/diveddie/d7b977e483f2ec486a3cf4f52bf9b409

For some reason, when I use your model.py script instead, my ComfyUI throws an error about not finding both Load and Apply modules forFlux IPAdapter. Do you have any idea what could be the issue? Cheers.
